// Code generated by the Encore 1.48.12 client generator. DO NOT EDIT.

// Disable eslint, jshint, and jslint for this file.
/* eslint-disable */
/* jshint ignore:start */
/*jslint-disable*/
import type { CookieWithOptions } from "encore.dev/api";

/**
 * BaseURL is the base URL for calling the Encore application's API.
 */
export type BaseURL = string

export const Local: BaseURL = "http://localhost:4000"

/**
 * Environment returns a BaseURL for calling the cloud environment with the given name.
 */
export function Environment(name: string): BaseURL {
    return `https://${name}-.encr.app`
}

/**
 * PreviewEnv returns a BaseURL for calling the preview environment with the given PR number.
 */
export function PreviewEnv(pr: number | string): BaseURL {
    return Environment(`pr${pr}`)
}

const BROWSER = typeof globalThis === "object" && ("window" in globalThis);

/**
 * Client is an API client for the  Encore application.
 */
export class Client {
    public readonly admin: admin.ServiceClient
    public readonly ai: ai.ServiceClient
    public readonly auth: auth.ServiceClient
    public readonly referrals: referrals.ServiceClient
    public readonly users: users.ServiceClient
    private readonly options: ClientOptions
    private readonly target: string


    /**
     * Creates a Client for calling the public and authenticated APIs of your Encore application.
     *
     * @param target  The target which the client should be configured to use. See Local and Environment for options.
     * @param options Options for the client
     */
    constructor(target: BaseURL, options?: ClientOptions) {
        this.target = target
        this.options = options ?? {}
        const base = new BaseClient(this.target, this.options)
        this.admin = new admin.ServiceClient(base)
        this.ai = new ai.ServiceClient(base)
        this.auth = new auth.ServiceClient(base)
        this.referrals = new referrals.ServiceClient(base)
        this.users = new users.ServiceClient(base)
    }

    /**
     * Creates a new Encore client with the given client options set.
     *
     * @param options Client options to set. They are merged with existing options.
     **/
    public with(options: ClientOptions): Client {
        return new Client(this.target, {
            ...this.options,
            ...options,
        })
    }
}

/**
 * Import the auth handler to be able to derive the auth type
 */
import type { auth as auth_auth } from "~backend/auth/auth";

/**
 * ClientOptions allows you to override any default behaviour within the generated Encore client.
 */
export interface ClientOptions {
    /**
     * By default the client will use the inbuilt fetch function for making the API requests.
     * however you can override it with your own implementation here if you want to run custom
     * code on each API request made or response received.
     */
    fetcher?: Fetcher

    /** Default RequestInit to be used for the client */
    requestInit?: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }

    /**
     * Allows you to set the authentication data to be used for each
     * request either by passing in a static object or by passing in
     * a function which returns a new object for each request.
     */
    auth?: RequestType<typeof auth_auth> | AuthDataGenerator
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import {
    bulkDeleteTeachers as api_admin_bulk_operations_bulkDeleteTeachers,
    bulkUpdateTeachers as api_admin_bulk_operations_bulkUpdateTeachers
} from "~backend/admin/bulk-operations";
import { getDashboardStats as api_admin_dashboard_stats_getDashboardStats } from "~backend/admin/dashboard-stats";
import {
    clearDemoData as api_admin_demo_data_clearDemoData,
    createDemoData as api_admin_demo_data_createDemoData
} from "~backend/admin/demo-data";
import { exportData as api_admin_export_data_exportData } from "~backend/admin/export-data";
import {
    getSystemSettings as api_admin_system_settings_getSystemSettings,
    updateSystemSettings as api_admin_system_settings_updateSystemSettings
} from "~backend/admin/system-settings";

export namespace admin {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.bulkDeleteTeachers = this.bulkDeleteTeachers.bind(this)
            this.bulkUpdateTeachers = this.bulkUpdateTeachers.bind(this)
            this.clearDemoData = this.clearDemoData.bind(this)
            this.createDemoData = this.createDemoData.bind(this)
            this.exportData = this.exportData.bind(this)
            this.getDashboardStats = this.getDashboardStats.bind(this)
            this.getSystemSettings = this.getSystemSettings.bind(this)
            this.updateSystemSettings = this.updateSystemSettings.bind(this)
        }

        /**
         * Bulk delete multiple teachers at once.
         */
        public async bulkDeleteTeachers(params: RequestType<typeof api_admin_bulk_operations_bulkDeleteTeachers>): Promise<ResponseType<typeof api_admin_bulk_operations_bulkDeleteTeachers>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/admin/teachers/bulk-delete`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_admin_bulk_operations_bulkDeleteTeachers>
        }

        /**
         * Bulk update multiple teachers at once.
         */
        public async bulkUpdateTeachers(params: RequestType<typeof api_admin_bulk_operations_bulkUpdateTeachers>): Promise<ResponseType<typeof api_admin_bulk_operations_bulkUpdateTeachers>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/admin/teachers/bulk-update`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_admin_bulk_operations_bulkUpdateTeachers>
        }

        /**
         * Clears all demo data from the system.
         */
        public async clearDemoData(): Promise<ResponseType<typeof api_admin_demo_data_clearDemoData>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/admin/demo/clear`, {method: "DELETE", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_admin_demo_data_clearDemoData>
        }

        /**
         * Creates demo data for testing and demonstrations.
         */
        public async createDemoData(params: RequestType<typeof api_admin_demo_data_createDemoData>): Promise<ResponseType<typeof api_admin_demo_data_createDemoData>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/admin/demo/create`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_admin_demo_data_createDemoData>
        }

        /**
         * Exports system data for admin analysis.
         */
        public async exportData(params: RequestType<typeof api_admin_export_data_exportData>): Promise<ResponseType<typeof api_admin_export_data_exportData>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/admin/export`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_admin_export_data_exportData>
        }

        /**
         * Gets comprehensive dashboard statistics for admin overview.
         */
        public async getDashboardStats(): Promise<ResponseType<typeof api_admin_dashboard_stats_getDashboardStats>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/admin/dashboard/stats`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_admin_dashboard_stats_getDashboardStats>
        }

        /**
         * Gets current system settings.
         */
        public async getSystemSettings(): Promise<ResponseType<typeof api_admin_system_settings_getSystemSettings>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/admin/system/settings`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_admin_system_settings_getSystemSettings>
        }

        /**
         * Updates system settings.
         */
        public async updateSystemSettings(params: RequestType<typeof api_admin_system_settings_updateSystemSettings>): Promise<ResponseType<typeof api_admin_system_settings_updateSystemSettings>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/admin/system/settings`, {method: "PUT", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_admin_system_settings_updateSystemSettings>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { followUpAssistance as api_ai_follow_up_assistance_followUpAssistance } from "~backend/ai/follow-up-assistance";
import { generateRecommendations as api_ai_generate_recommendations_generateRecommendations } from "~backend/ai/generate-recommendations";

export namespace ai {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.followUpAssistance = this.followUpAssistance.bind(this)
            this.generateRecommendations = this.generateRecommendations.bind(this)
        }

        /**
         * Provides follow-up assistance for implementing Tier 2 interventions.
         */
        public async followUpAssistance(params: RequestType<typeof api_ai_follow_up_assistance_followUpAssistance>): Promise<ResponseType<typeof api_ai_follow_up_assistance_followUpAssistance>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ai/follow-up-assistance`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ai_follow_up_assistance_followUpAssistance>
        }

        /**
         * Generates Tier 2 intervention recommendations based on student information and concerns.
         */
        public async generateRecommendations(params: RequestType<typeof api_ai_generate_recommendations_generateRecommendations>): Promise<ResponseType<typeof api_ai_generate_recommendations_generateRecommendations>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ai/recommendations`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ai_generate_recommendations_generateRecommendations>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { adminLogin as api_auth_admin_login_adminLogin } from "~backend/auth/admin-login";
import { adminLogout as api_auth_admin_logout_adminLogout } from "~backend/auth/admin-logout";

export namespace auth {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.adminLogin = this.adminLogin.bind(this)
            this.adminLogout = this.adminLogout.bind(this)
        }

        /**
         * Admin login for demo purposes.
         */
        public async adminLogin(params: RequestType<typeof api_auth_admin_login_adminLogin>): Promise<ResponseType<typeof api_auth_admin_login_adminLogin>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/auth/admin/login`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_auth_admin_login_adminLogin>
        }

        /**
         * Admin logout for demo purposes.
         */
        public async adminLogout(): Promise<ResponseType<typeof api_auth_admin_logout_adminLogout>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/auth/admin/logout`, {method: "POST", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_auth_admin_logout_adminLogout>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { create as api_referrals_create_create } from "~backend/referrals/create";
import { generatePDF as api_referrals_generate_pdf_generatePDF } from "~backend/referrals/generate-pdf";
import { get as api_referrals_get_get } from "~backend/referrals/get";
import { list as api_referrals_list_list } from "~backend/referrals/list";
import { shareEmail as api_referrals_share_email_shareEmail } from "~backend/referrals/share-email";

export namespace referrals {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.create = this.create.bind(this)
            this.generatePDF = this.generatePDF.bind(this)
            this.get = this.get.bind(this)
            this.list = this.list.bind(this)
            this.shareEmail = this.shareEmail.bind(this)
        }

        /**
         * Creates a new student support request form.
         */
        public async create(params: RequestType<typeof api_referrals_create_create>): Promise<ResponseType<typeof api_referrals_create_create>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/referrals`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_referrals_create_create>
        }

        /**
         * Generates a PDF report for a support request suitable for student support meetings.
         */
        public async generatePDF(params: { supportRequestId: number }): Promise<ResponseType<typeof api_referrals_generate_pdf_generatePDF>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/referrals/${encodeURIComponent(params.supportRequestId)}/pdf`, {method: "POST", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_referrals_generate_pdf_generatePDF>
        }

        /**
         * Retrieves a single support request by ID.
         */
        public async get(params: { id: number }): Promise<ResponseType<typeof api_referrals_get_get>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/referrals/${encodeURIComponent(params.id)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_referrals_get_get>
        }

        /**
         * Retrieves all support requests, optionally filtered by teacher.
         */
        public async list(params: RequestType<typeof api_referrals_list_list>): Promise<ResponseType<typeof api_referrals_list_list>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit:   params.limit === undefined ? undefined : String(params.limit),
                teacher: params.teacher,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/referrals`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_referrals_list_list>
        }

        /**
         * Shares a support request via email for student support meetings.
         */
        public async shareEmail(params: RequestType<typeof api_referrals_share_email_shareEmail>): Promise<ResponseType<typeof api_referrals_share_email_shareEmail>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                message:        params.message,
                recipientEmail: params.recipientEmail,
                senderName:     params.senderName,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/referrals/${encodeURIComponent(params.supportRequestId)}/share`, {method: "POST", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_referrals_share_email_shareEmail>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { checkAccess as api_users_check_access_checkAccess } from "~backend/users/check-access";
import { createUserByAdmin as api_users_create_user_by_admin_createUserByAdmin } from "~backend/users/create-user-by-admin";
import { deleteUserByAdmin as api_users_delete_user_by_admin_deleteUserByAdmin } from "~backend/users/delete-user-by-admin";
import { getProfile as api_users_get_profile_getProfile } from "~backend/users/get-profile";
import { listUsers as api_users_list_users_listUsers } from "~backend/users/list-users";
import { purchaseSupportRequestPackage as api_users_purchase_referral_package_purchaseSupportRequestPackage } from "~backend/users/purchase-referral-package";
import { updateProfile as api_users_update_profile_updateProfile } from "~backend/users/update-profile";
import { updateUserByAdmin as api_users_update_user_by_admin_updateUserByAdmin } from "~backend/users/update-user-by-admin";

export namespace users {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.checkAccess = this.checkAccess.bind(this)
            this.createUserByAdmin = this.createUserByAdmin.bind(this)
            this.deleteUserByAdmin = this.deleteUserByAdmin.bind(this)
            this.getProfile = this.getProfile.bind(this)
            this.listUsers = this.listUsers.bind(this)
            this.purchaseSupportRequestPackage = this.purchaseSupportRequestPackage.bind(this)
            this.updateProfile = this.updateProfile.bind(this)
            this.updateUserByAdmin = this.updateUserByAdmin.bind(this)
        }

        /**
         * Checks if the authenticated user has access to a specific feature based on their subscription.
         */
        public async checkAccess(): Promise<ResponseType<typeof api_users_check_access_checkAccess>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/users/check-access`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_users_check_access_checkAccess>
        }

        /**
         * Creates a new user (teacher). For admins only.
         */
        public async createUserByAdmin(params: RequestType<typeof api_users_create_user_by_admin_createUserByAdmin>): Promise<ResponseType<typeof api_users_create_user_by_admin_createUserByAdmin>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/users/admin/create`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_users_create_user_by_admin_createUserByAdmin>
        }

        /**
         * Deletes a user. For admins only.
         */
        public async deleteUserByAdmin(params: { id: number }): Promise<ResponseType<typeof api_users_delete_user_by_admin_deleteUserByAdmin>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/users/admin/${encodeURIComponent(params.id)}`, {method: "DELETE", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_users_delete_user_by_admin_deleteUserByAdmin>
        }

        /**
         * Retrieves the authenticated user's profile information.
         */
        public async getProfile(): Promise<ResponseType<typeof api_users_get_profile_getProfile>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/users/profile`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_users_get_profile_getProfile>
        }

        /**
         * Lists all users in the system. For admins only.
         */
        public async listUsers(): Promise<ResponseType<typeof api_users_list_users_listUsers>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/users/admin/list`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_users_list_users_listUsers>
        }

        /**
         * Purchases additional support request packages for the authenticated user.
         */
        public async purchaseSupportRequestPackage(params: RequestType<typeof api_users_purchase_referral_package_purchaseSupportRequestPackage>): Promise<ResponseType<typeof api_users_purchase_referral_package_purchaseSupportRequestPackage>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/users/purchase-support-request-package`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_users_purchase_referral_package_purchaseSupportRequestPackage>
        }

        /**
         * Updates the authenticated user's profile information.
         */
        public async updateProfile(params: RequestType<typeof api_users_update_profile_updateProfile>): Promise<ResponseType<typeof api_users_update_profile_updateProfile>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/users/profile`, {method: "PUT", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_users_update_profile_updateProfile>
        }

        /**
         * Updates a user's profile. For admins only.
         */
        public async updateUserByAdmin(params: RequestType<typeof api_users_update_user_by_admin_updateUserByAdmin>): Promise<ResponseType<typeof api_users_update_user_by_admin_updateUserByAdmin>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                email:                params.email,
                name:                 params.name,
                schoolDistrict:       params.schoolDistrict,
                schoolName:           params.schoolName,
                subscriptionEndDate:  params.subscriptionEndDate,
                supportRequestsLimit: params.supportRequestsLimit,
                teacherType:          params.teacherType,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/users/admin/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_users_update_user_by_admin_updateUserByAdmin>
        }
    }
}


type PickMethods<Type> = Omit<CallParameters, "method"> & { method?: Type };

// Helper type to omit all fields that are cookies.
type OmitCookie<T> = {
  [K in keyof T as T[K] extends CookieWithOptions<any> ? never : K]: T[K];
};

type RequestType<Type extends (...args: any[]) => any> =
  Parameters<Type> extends [infer H, ...any[]]
    ? OmitCookie<H>
    : void;

type ResponseType<Type extends (...args: any[]) => any> = OmitCookie<Awaited<ReturnType<Type>>>;

function dateReviver(key: string, value: any): any {
  if (
    typeof value === "string" &&
    value.length >= 10 &&
    value.charCodeAt(0) >= 48 && // '0'
    value.charCodeAt(0) <= 57 // '9'
  ) {
    const parsedDate = new Date(value);
    if (!isNaN(parsedDate.getTime())) {
      return parsedDate;
    }
  }
  return value;
}


function encodeQuery(parts: Record<string, string | string[]>): string {
    const pairs: string[] = []
    for (const key in parts) {
        const val = (Array.isArray(parts[key]) ?  parts[key] : [parts[key]]) as string[]
        for (const v of val) {
            pairs.push(`${key}=${encodeURIComponent(v)}`)
        }
    }
    return pairs.join("&")
}

// makeRecord takes a record and strips any undefined values from it,
// and returns the same record with a narrower type.
// @ts-ignore - TS ignore because makeRecord is not always used
function makeRecord<K extends string | number | symbol, V>(record: Record<K, V | undefined>): Record<K, V> {
    for (const key in record) {
        if (record[key] === undefined) {
            delete record[key]
        }
    }
    return record as Record<K, V>
}

import {
  StreamInOutHandlerFn,
  StreamInHandlerFn,
  StreamOutHandlerFn,
} from "encore.dev/api";

type StreamRequest<Type> = Type extends
  | StreamInOutHandlerFn<any, infer Req, any>
  | StreamInHandlerFn<any, infer Req, any>
  | StreamOutHandlerFn<any, any>
  ? Req
  : never;

type StreamResponse<Type> = Type extends
  | StreamInOutHandlerFn<any, any, infer Resp>
  | StreamInHandlerFn<any, any, infer Resp>
  | StreamOutHandlerFn<any, infer Resp>
  ? Resp
  : never;


function encodeWebSocketHeaders(headers: Record<string, string>) {
    // url safe, no pad
    const base64encoded = btoa(JSON.stringify(headers))
      .replaceAll("=", "")
      .replaceAll("+", "-")
      .replaceAll("/", "_");
    return "encore.dev.headers." + base64encoded;
}

class WebSocketConnection {
    public ws: WebSocket;

    private hasUpdateHandlers: (() => void)[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        let protocols = ["encore-ws"];
        if (headers) {
            protocols.push(encodeWebSocketHeaders(headers))
        }

        this.ws = new WebSocket(url, protocols)

        this.on("error", () => {
            this.resolveHasUpdateHandlers();
        });

        this.on("close", () => {
            this.resolveHasUpdateHandlers();
        });
    }

    resolveHasUpdateHandlers() {
        const handlers = this.hasUpdateHandlers;
        this.hasUpdateHandlers = [];

        for (const handler of handlers) {
            handler()
        }
    }

    async hasUpdate() {
        // await until a new message have been received, or the socket is closed
        await new Promise((resolve) => {
            this.hasUpdateHandlers.push(() => resolve(null))
        });
    }

    on(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.addEventListener(type, handler);
    }

    off(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.removeEventListener(type, handler);
    }

    close() {
        this.ws.close();
    }
}

export class StreamInOut<Request, Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data, dateReviver));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamIn<Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data, dateReviver));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamOut<Request, Response> {
    public socket: WebSocketConnection;
    private responseValue: Promise<Response>;

    constructor(url: string, headers?: Record<string, string>) {
        let responseResolver: (_: any) => void;
        this.responseValue = new Promise((resolve) => responseResolver = resolve);

        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            responseResolver(JSON.parse(event.data, dateReviver))
        });
    }

    async response(): Promise<Response> {
        return this.responseValue;
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }
}
// CallParameters is the type of the parameters to a method call, but require headers to be a Record type
type CallParameters = Omit<RequestInit, "headers"> & {
    /** Headers to be sent with the request */
    headers?: Record<string, string>

    /** Query parameters to be sent with the request */
    query?: Record<string, string | string[]>
}

// AuthDataGenerator is a function that returns a new instance of the authentication data required by this API
export type AuthDataGenerator = () =>
  | RequestType<typeof auth_auth>
  | Promise<RequestType<typeof auth_auth> | undefined>
  | undefined;

// A fetcher is the prototype for the inbuilt Fetch function
export type Fetcher = typeof fetch;

const boundFetch = fetch.bind(this);

class BaseClient {
    readonly baseURL: string
    readonly fetcher: Fetcher
    readonly headers: Record<string, string>
    readonly requestInit: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }
    readonly authGenerator?: AuthDataGenerator

    constructor(baseURL: string, options: ClientOptions) {
        this.baseURL = baseURL
        this.headers = {}

        // Add User-Agent header if the script is running in the server
        // because browsers do not allow setting User-Agent headers to requests
        if (!BROWSER) {
            this.headers["User-Agent"] = "-Generated-TS-Client (Encore/1.48.12)";
        }

        this.requestInit = options.requestInit ?? {};

        // Setup what fetch function we'll be using in the base client
        if (options.fetcher !== undefined) {
            this.fetcher = options.fetcher
        } else {
            this.fetcher = boundFetch
        }

        // Setup an authentication data generator using the auth data token option
        if (options.auth !== undefined) {
            const auth = options.auth
            if (typeof auth === "function") {
                this.authGenerator = auth
            } else {
                this.authGenerator = () => auth
            }
        }
    }

    async getAuthData(): Promise<CallParameters | undefined> {
        let authData: RequestType<typeof auth_auth> | undefined;

        // If authorization data generator is present, call it and add the returned data to the request
        if (this.authGenerator) {
            const mayBePromise = this.authGenerator();
            if (mayBePromise instanceof Promise) {
                authData = await mayBePromise;
            } else {
                authData = mayBePromise;
            }
        }

        if (authData) {
            const data: CallParameters = {};

            data.headers = makeRecord<string, string>({
                authorization: authData.authorization,
            });

            return data;
        }

        return undefined;
    }

    // createStreamInOut sets up a stream to a streaming API endpoint.
    async createStreamInOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamInOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamInOut(this.baseURL + path + queryString, headers);
    }

    // createStreamIn sets up a stream to a streaming API endpoint.
    async createStreamIn<Response>(path: string, params?: CallParameters): Promise<StreamIn<Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamIn(this.baseURL + path + queryString, headers);
    }

    // createStreamOut sets up a stream to a streaming API endpoint.
    async createStreamOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamOut(this.baseURL + path + queryString, headers);
    }

    // callTypedAPI makes an API call, defaulting content type to "application/json"
    public async callTypedAPI(path: string, params?: CallParameters): Promise<Response> {
        return this.callAPI(path, {
            ...params,
            headers: { "Content-Type": "application/json", ...params?.headers }
        });
    }

    // callAPI is used by each generated API method to actually make the request
    public async callAPI(path: string, params?: CallParameters): Promise<Response> {
        let { query, headers, ...rest } = params ?? {}
        const init = {
            ...this.requestInit,
            ...rest,
        }

        // Merge our headers with any predefined headers
        init.headers = {...this.headers, ...init.headers, ...headers}

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                init.headers = {...init.headers, ...authData.headers};
            }
        }

        // Make the actual request
        const queryString = query ? '?' + encodeQuery(query) : ''
        const response = await this.fetcher(this.baseURL+path+queryString, init)

        // handle any error responses
        if (!response.ok) {
            // try and get the error message from the response body
            let body: APIErrorResponse = { code: ErrCode.Unknown, message: `request failed: status ${response.status}` }

            // if we can get the structured error we should, otherwise give a best effort
            try {
                const text = await response.text()

                try {
                    const jsonBody = JSON.parse(text)
                    if (isAPIErrorResponse(jsonBody)) {
                        body = jsonBody
                    } else {
                        body.message += ": " + JSON.stringify(jsonBody)
                    }
                } catch {
                    body.message += ": " + text
                }
            } catch (e) {
                // otherwise we just append the text to the error message
                body.message += ": " + String(e)
            }

            throw new APIError(response.status, body)
        }

        return response
    }
}

/**
 * APIErrorDetails represents the response from an Encore API in the case of an error
 */
interface APIErrorResponse {
    code: ErrCode
    message: string
    details?: any
}

function isAPIErrorResponse(err: any): err is APIErrorResponse {
    return (
        err !== undefined && err !== null &&
        isErrCode(err.code) &&
        typeof(err.message) === "string" &&
        (err.details === undefined || err.details === null || typeof(err.details) === "object")
    )
}

function isErrCode(code: any): code is ErrCode {
    return code !== undefined && Object.values(ErrCode).includes(code)
}

/**
 * APIError represents a structured error as returned from an Encore application.
 */
export class APIError extends Error {
    /**
     * The HTTP status code associated with the error.
     */
    public readonly status: number

    /**
     * The Encore error code
     */
    public readonly code: ErrCode

    /**
     * The error details
     */
    public readonly details?: any

    constructor(status: number, response: APIErrorResponse) {
        // extending errors causes issues after you construct them, unless you apply the following fixes
        super(response.message);

        // set error name as constructor name, make it not enumerable to keep native Error behavior
        // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target#new.target_in_constructors
        Object.defineProperty(this, 'name', {
            value:        'APIError',
            enumerable:   false,
            configurable: true,
        })

        // fix the prototype chain
        if ((Object as any).setPrototypeOf == undefined) {
            (this as any).__proto__ = APIError.prototype
        } else {
            Object.setPrototypeOf(this, APIError.prototype);
        }

        // capture a stack trace
        if ((Error as any).captureStackTrace !== undefined) {
            (Error as any).captureStackTrace(this, this.constructor);
        }

        this.status = status
        this.code = response.code
        this.details = response.details
    }
}

/**
 * Typeguard allowing use of an APIError's fields'
 */
export function isAPIError(err: any): err is APIError {
    return err instanceof APIError;
}

export enum ErrCode {
    /**
     * OK indicates the operation was successful.
     */
    OK = "ok",

    /**
     * Canceled indicates the operation was canceled (typically by the caller).
     *
     * Encore will generate this error code when cancellation is requested.
     */
    Canceled = "canceled",

    /**
     * Unknown error. An example of where this error may be returned is
     * if a Status value received from another address space belongs to
     * an error-space that is not known in this address space. Also
     * errors raised by APIs that do not return enough error information
     * may be converted to this error.
     *
     * Encore will generate this error code in the above two mentioned cases.
     */
    Unknown = "unknown",

    /**
     * InvalidArgument indicates client specified an invalid argument.
     * Note that this differs from FailedPrecondition. It indicates arguments
     * that are problematic regardless of the state of the system
     * (e.g., a malformed file name).
     *
     * This error code will not be generated by the gRPC framework.
     */
    InvalidArgument = "invalid_argument",

    /**
     * DeadlineExceeded means operation expired before completion.
     * For operations that change the state of the system, this error may be
     * returned even if the operation has completed successfully. For
     * example, a successful response from a server could have been delayed
     * long enough for the deadline to expire.
     *
     * The gRPC framework will generate this error code when the deadline is
     * exceeded.
     */
    DeadlineExceeded = "deadline_exceeded",

    /**
     * NotFound means some requested entity (e.g., file or directory) was
     * not found.
     *
     * This error code will not be generated by the gRPC framework.
     */
    NotFound = "not_found",

    /**
     * AlreadyExists means an attempt to create an entity failed because one
     * already exists.
     *
     * This error code will not be generated by the gRPC framework.
     */
    AlreadyExists = "already_exists",

    /**
     * PermissionDenied indicates the caller does not have permission to
     * execute the specified operation. It must not be used for rejections
     * caused by exhausting some resource (use ResourceExhausted
     * instead for those errors). It must not be
     * used if the caller cannot be identified (use Unauthenticated
     * instead for those errors).
     *
     * This error code will not be generated by the gRPC core framework,
     * but expect authentication middleware to use it.
     */
    PermissionDenied = "permission_denied",

    /**
     * ResourceExhausted indicates some resource has been exhausted, perhaps
     * a per-user quota, or perhaps the entire file system is out of space.
     *
     * This error code will be generated by the gRPC framework in
     * out-of-memory and server overload situations, or when a message is
     * larger than the configured maximum size.
     */
    ResourceExhausted = "resource_exhausted",

    /**
     * FailedPrecondition indicates operation was rejected because the
     * system is not in a state required for the operation's execution.
     * For example, directory to be deleted may be non-empty, an rmdir
     * operation is applied to a non-directory, etc.
     *
     * A litmus test that may help a service implementor in deciding
     * between FailedPrecondition, Aborted, and Unavailable:
     *  (a) Use Unavailable if the client can retry just the failing call.
     *  (b) Use Aborted if the client should retry at a higher-level
     *      (e.g., restarting a read-modify-write sequence).
     *  (c) Use FailedPrecondition if the client should not retry until
     *      the system state has been explicitly fixed. E.g., if an "rmdir"
     *      fails because the directory is non-empty, FailedPrecondition
     *      should be returned since the client should not retry unless
     *      they have first fixed up the directory by deleting files from it.
     *  (d) Use FailedPrecondition if the client performs conditional
     *      REST Get/Update/Delete on a resource and the resource on the
     *      server does not match the condition. E.g., conflicting
     *      read-modify-write on the same resource.
     *
     * This error code will not be generated by the gRPC framework.
     */
    FailedPrecondition = "failed_precondition",

    /**
     * Aborted indicates the operation was aborted, typically due to a
     * concurrency issue like sequencer check failures, transaction aborts,
     * etc.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     */
    Aborted = "aborted",

    /**
     * OutOfRange means operation was attempted past the valid range.
     * E.g., seeking or reading past end of file.
     *
     * Unlike InvalidArgument, this error indicates a problem that may
     * be fixed if the system state changes. For example, a 32-bit file
     * system will generate InvalidArgument if asked to read at an
     * offset that is not in the range [0,2^32-1], but it will generate
     * OutOfRange if asked to read from an offset past the current
     * file size.
     *
     * There is a fair bit of overlap between FailedPrecondition and
     * OutOfRange. We recommend using OutOfRange (the more specific
     * error) when it applies so that callers who are iterating through
     * a space can easily look for an OutOfRange error to detect when
     * they are done.
     *
     * This error code will not be generated by the gRPC framework.
     */
    OutOfRange = "out_of_range",

    /**
     * Unimplemented indicates operation is not implemented or not
     * supported/enabled in this service.
     *
     * This error code will be generated by the gRPC framework. Most
     * commonly, you will see this error code when a method implementation
     * is missing on the server. It can also be generated for unknown
     * compression algorithms or a disagreement as to whether an RPC should
     * be streaming.
     */
    Unimplemented = "unimplemented",

    /**
     * Internal errors. Means some invariants expected by underlying
     * system has been broken. If you see one of these errors,
     * something is very broken.
     *
     * This error code will be generated by the gRPC framework in several
     * internal error conditions.
     */
    Internal = "internal",

    /**
     * Unavailable indicates the service is currently unavailable.
     * This is a most likely a transient condition and may be corrected
     * by retrying with a backoff. Note that it is not always safe to retry
     * non-idempotent operations.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     *
     * This error code will be generated by the gRPC framework during
     * abrupt shutdown of a server process or network connection.
     */
    Unavailable = "unavailable",

    /**
     * DataLoss indicates unrecoverable data loss or corruption.
     *
     * This error code will not be generated by the gRPC framework.
     */
    DataLoss = "data_loss",

    /**
     * Unauthenticated indicates the request does not have valid
     * authentication credentials for the operation.
     *
     * The gRPC framework will generate this error code when the
     * authentication metadata is invalid or a Credentials callback fails,
     * but also expect authentication middleware to generate it.
     */
    Unauthenticated = "unauthenticated",
}

export default new Client(import.meta.env.VITE_CLIENT_TARGET, { requestInit: { credentials: "include" } });
